
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv

spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mariadb
  hostPath:
    path: "/run/desktop/mnt/host/Users/kmj/developer/common-kubernetes/mariadb/database"